language: node_js

node_js:
- 12
- 14

deploy:
  provider: npm
  email: aler9.dev@gmail.com
  api_key:
    secure: $NPM_API_KEY
  on:
    repo: aler9/googlefonts-inliner
    tags: true
    node_js: 14
