name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - run: yarn install

    - run: make test-nodocker
